version: "3"
services:
  app:
    image: node:lts-alpine
    command: yarn serve --mode development
    env_file: .env.development
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
