name: Auto Sync Main Into Pod Branches
on:
  push:
    branches:
      - main

jobs:
  green:
    name: Green
    runs-on: ubuntu-latest
    steps:
      - id: pod-green
        uses: actions/autosync-openpr@v1
        with:
          mergeInto: 'pod-green'
  indigo:
    name: Indigo
    runs-on: ubuntu-latest
    steps:
      - id: pod-indigo
        uses: actions/autosync-openpr@v1
        with:
          mergeInto: 'pod-indigo'
  red:
    name: Red
    runs-on: ubuntu-latest
    steps:
      - id: pod-red
        uses: actions/autosync-openpr@v1
        with:
          mergeInto: 'pod-red'
