name: Auto Sync Master Into Pod Branches
on:
  push:
    branches:
      - main

jobs:
  green:
    name: Green
    runs-on: ubuntu-latest
    steps:
      - name: Open Auto Sync PR
        id: pr_open
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "pod-green"
      - name: Merge Auto Sync PR
        uses: "actions/github-script@v3"
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const repository = context.repo
            await github.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: ${{ steps.pr_open.outputs.PULL_REQUEST_NUMBER }},
              repo: repository.repo,
            })

  indigo:
    name: Indigo
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: pr_open
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "pod-indigo"
      - name: Merge PR
        uses: "actions/github-script@v3"
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const repository = context.repo
            await github.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: ${{ steps.pr_open.outputs.PULL_REQUEST_NUMBER }},
              repo: repository.repo,
            })

  red:
    name: Red
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: pr_open
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "pod-red"
      - name: Merge PR
        uses: "actions/github-script@v3"
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const repository = context.repo
            await github.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: ${{ steps.pr_open.outputs.PULL_REQUEST_NUMBER }},
              repo: repository.repo,
            })
